create table if not exists member
(
    id       bigint generated by default as identity,
    email    varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
    );

create table if not exists product
(
    id        bigint generated by default as identity,
    name      varchar(15)  not null,
    image_url varchar(255) not null,
    price     integer      not null,
    primary key (id)
    );

create table if not exists wish
(
    id         bigint generated by default as identity,
    member_id  bigint not null,
    product_id bigint not null,
    quantity   int    not null,
    primary key (id),

    constraint fk_wish_member_id_ref_member_id
    foreign key (member_id) references member,

    constraint fk_wish_product_id_ref_product_id
    foreign key (product_id) references product
    );
